version: "3"

services:
  sharpnet:
    hostname: sharpnet
    image: sharp6292/sharpnet

    restart: always

    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"

    environment:
      - "DEV=${DEV}"

    volumes:
      - certs:/etc/letsencrypt/
      - "/var/run/docker.sock:/var/run/docker.sock"


networks:
    default:
        external:
            name: ${NETWORK}

volumes:
  certs: