version: "3"

services:
  sharpnet:
    hostname: sharpnet
    image: sharp6292/sharpnet
    restart: always

    ports:
      - "${HTTP_PORT:?err}:80"
      - "${HTTPS_PORT:?err}:443"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      - "DEV=${DEV:?err}"
      - "MAILPASS=${MAILPASS:?err}"
      - "SENDER_EMAIL=${SENDER_EMAIL:?err}"
      - "RECEIVER_EMAIL=${RECEIVER_EMAIL:?err}"
      - "DOMAIN=${DOMAIN:?err}"

    volumes:
      - certs:/etc/letsencrypt/
      - "/var/run/docker.sock:/var/run/docker.sock"


networks:
    default:
        external:
            name: ${NETWORK:?err}

volumes:
  certs: