version: "3"

services:
  mcacorp_nginx:
    hostname: mcacorp_nginx
    build: .
    ports:
      - "${PORT}:80"
      - "443:433"

    volumes:
      - webcode:/code
      - certs:/etc/letsencrypt/

volumes:
  certs:
  webcode:
      external: true

networks:
    default:
        external:
            name: mca-corp