version: "3"

services:
  sharpnet:
    hostname: sharpnet
    build: .
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"

    environment:
      - "PRODUCTION=${PRODUCTION}"

    volumes:
      - certs:/etc/letsencrypt/
      - "/var/run/docker.sock:/var/run/docker.sock"


networks:
    default:
        external:
            name: sharpnet_testing

volumes:
  certs: