version: 2.1

orbs:
  docker: sharptools/docker@volatile
  sharpcd: sharptools/sharpcd@volatile

jobs:
  deploy:
    docker:
      - image: cimg/base:2020.01

    steps:
      - sharpcd/install

      - run:
          name: "Setup Env"
          command: |
            echo "HTTP_PORT=80" > .env
            echo "HTTPS_PORT=443" >> .env
            echo "DEV=FALSE" >> .env
            echo "NETWORK=sharpnet" >> .env
            echo "MAILPASS=${MAILPASS}" >> .env
            echo "SENDER_EMAIL=${SENDER_EMAIL}" >> .env
            echo "RECEIVER_EMAIL=${RECEIVER_EMAIL}" >> .env
            echo "DOMAIN=${DOMAIN}" >> .env

            echo "HTTP_PORT=80" > .env2
            echo "HTTPS_PORT=443" >> .env2
            echo "DEV=FALSE" >> .env2
            echo "NETWORK=sharpnet" >> .env2
            echo "MAILPASS=${MAILPASS}" >> .env2
            echo "SENDER_EMAIL=${SENDER_EMAIL}" >> .env2
            echo "RECEIVER_EMAIL=${RECEIVER_EMAIL}" >> .env2
            echo "DOMAIN=${DOMAIN_CORP}" >> .env2

      - sharpcd/deploy

workflows:
  version: 2
  workflow:
    jobs:
      - docker/build_wait:
          context: General
          image: sharp6292/sharpnet:latest


      - deploy:
          context: General
          requires:
            - docker/build_wait

          filters:
            branches:
              only: master
